version: '3.8'

services:
  note-god:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_SOCKET_SERVER_URL=${NEXT_PUBLIC_SOCKET_SERVER_URL}
    container_name: note-god
    ports:
      - '3000:3000'
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - workers
      - socket-server
      - qdrant
      - redis
    command: sh -c "npx prisma migrate deploy && npm start"

  workers:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: note-god-workers
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - redis
      - qdrant
    command: npm run start:worker

  socket-server:
    build:
      context: .
      dockerfile: socket-server/Dockerfile
    container_name: socket-server
    ports:
      - '4000:4000'
    env_file:
      - ./socket-server/.env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    restart: unless-stopped
    depends_on:
      - redis

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  redis_data:
  qdrant_data:
